### PR TITLE
Align with HL7 SE and adjust SCT version

### PR DESCRIPTION
**Pull request by peturv**
#21 Alignment of Organization and Patient with HL7SE
#29  SCT version adjusted according to decision

### CODE REVIEW

**Comment by peturv** [comment]
A lot of files have changed due to updates of HL7SE profiles that are included in our repository. The relevant changes are mainly in the `fsh` catalog.

**Review by vjernelov — APPROVED** [review]
Couldn't find any errors when I looked through the changes.

Some of the SEBase-types were rendered as a single line though, making the review quite difficult.

**Review by RebeckaHansson — APPROVED** [review]
Looks good to me!

**Review by RebeckaHansson — APPROVED** [review]
Looks good 👍

**Pull request merged**
