### PR TITLE
Fixed regex to only allow 10 digits

### LINKED ISSUE #73: Fix for organisationsnummer-invariant
The organisationsnummer-invariant currently has the following regex:

> $this.toString().matches('\\\\d{10}')

This would allow a string of >10 characters, as long as there somewhere in that string are 10 digits in a row.

A more correct way of writing the invariant check would be to use the following regex:

> $this.toString().matches('^\\\\d{10}$')

which would actively restrict the string to only 10 digits.

EDIT: Adding regex in a comment apparently destroys everything...

### PR DESCRIPTION
**Pull request by vjernelov**
Updated the regex to only allow for 10 digits, as opposed to the previous version which allowed for any string as long as it contained 10 digits in a row somewhere in the string.

### CODE REVIEW

**Review by MangalaEkanayake — APPROVED** [review]

**Review by peturv — APPROVED** [review]

**Comment by peturv** [comment]
For some reason the IG build bot hasn't been able to clone this specific branch to build. Unsure why since it's been building other branches.
Have you tested a local build?

**Comment by vjernelov** [comment]
No, don't have local IG builds set up on my computer @peturv . Does it mean we can't tell if computer will say yes or no?

**Comment by peturv** [comment]
I did a local build now with warnings (unsure if there are any added to our normal amount of warnings), but no errors. It should be good!

**Comment by vjernelov** [comment]
Ok, waiting for @vadi2 to shoot down the regex then :)

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
